### ISSUE TITLE
compared to other packages `from grblas import ...` is 10 times slower

### ISSUE THREAD

**Issue by ParticularMiner** [metagraph-dev/grblas#130]
Hi @eriknw 

This may be a minor issue which I noticed a while back: `from grblas import ...` is unexpectedly slow.  Pls take a look at this [notebook](https://github.com/ParticularMiner/grblas/blob/import/notebooks/import_times.ipynb) and let me know if my concern is valid.

**Comment by eriknw** [comment]
Yeah, this is a pain point and is a valid issue.  Thanks for raising it.

Profiling reveals that the majority of time is spent creating new BinaryOp objects: `floordiv`, `rfloordiv`, `absfirst`, `abssecond`, `isclose`, and `numpy.mod`.  We compile these with numba, which is slow.  We should be able to speed up imports by registering these *lazily* and only compile them if and when they're used.

`grblas` has a lot of dependencies to import such as numpy, pandas, scipy, and numba, and using cffi bindings to GraphBLAS can also be slow when initializing.  So, we can make importing `grblas` much faster, but it probably won't ever be "fast".  I may someday find the time to continue with `cygraphblas` (which is basically Cythonized `grblas`), which I expect will be much faster to import (and to use).
