### ISSUE TITLE
Allow reduce to scalar to result in empty scalar

### ISSUE THREAD

**Issue by eriknw** [metagraph-dev/grblas#160]
It would be nice to have an option to allow reduce to scalar to result in an empty scalar rather than the monoid identity.  By adding this to the API, we can make some of the aggregators in `dask-grblas` much faster by not requiring computing `nvals`.

@jim22k what do you think?  What's a good keyword?  `C.reduce_scalar(allow_empty=True)`?  Default `True` or `False`?

Perhaps we should bubble this up to SuiteSparse:GraphBLAS to e.g. allow the behavior to be toggled via a descriptor.

CC @ParticularMiner

**Comment by jim22k** [comment]
> @jim22k what do you think? What's a good keyword? `C.reduce_scalar(allow_empty=True)`? Default `True` or `False`?

This looks like a reasonable spelling to me (including the default of True).

**Comment by eriknw** [comment]
Thanks for chiming in.

I think I'm okay with changing the default to `allow_empty=True`, even though it's changing default behavior for normal reductions.  I don't have a strong opinion on this, but I do think `C.reduce_scalar(allow_empty=False)` is kind of weird spelling to use the monoid identity if `C` is empty.  Also, we should probably raise for aggregators with `allow_empty=False`, which is an argument in favor of having a default of `True`.
