### ISSUE TITLE
Option to return native values or numpy values in `to_values`

### ISSUE THREAD

**Issue by eriknw** [metagraph-dev/grblas#39]
For example, `to_values` and `from_values` can be used to create a diagonal matrix:
```python
index, vals = my_vector.to_values()
D = Matrix.from_values(index, index, vals, ncols=my_vector.size, nrows=my_vector.size)
```
This would be more efficient if the values were native instead of being converted to/from tuples.

It's possible/reasonable to create a numpy array from cffi arrays, so perhaps methods like `to_arrays` or `from_numpy` would be appropriate.

**Comment by jim22k** [comment]
Could we simply standardize on `ndarray` for output and allow many types of input (`ndarray`, `tuple`, `list`)? 

If the `ndarray` can be created from native cffi and converted to native cffi, that seems like the best approach.

**Comment by eriknw** [comment]
Yeah, that's a good approach, but I think it'll be annoying to get it right though.  Maybe not though as long as we have thorough tests!

**Comment by eriknw** [comment]
Implemented in https://github.com/metagraph-dev/grblas/pull/57 and updated in https://github.com/metagraph-dev/grblas/pull/63

Closing.
