### ISSUE TITLE
Should we detect DimensionMismatch sooner?

### ISSUE THREAD

**Issue by eriknw** [metagraph-dev/grblas#40]
For example, that `A.shape == B.shape` in `A.ewise_add(B)`, or that `A.ncols == B.nrows` in `A.mxm(B)`.

Now that delayed expressions are getting nicer reprs, it may be nice to detect these upon first creating the delayed expression.  Otherwise, it feels weird to look

The main downsides are a tiny performance hit and that our error message may be different from what people are used to from the underlying implementation.  A positive is that we'd have a consistent error message independent of implementation.

**Comment by jim22k** [comment]
How wide-spread would the dimension checking be? Are we checking mask shape, output shape? What about indexes for assign and extract?

I'm not opposed to doing this, but we should decide just how complete we want the solution to be and whether that amount of checking becomes a performance hit.

**Comment by eriknw** [comment]
I suspect there's enough overhead already that adding `A.ncols == B.nrows` check will be insignificant.  If overhead becomes a bigger concern, then I think Cython is a viable option.

My current thinking is that we should limit this to quick checks for things that are obviously bad when creating delayed expressions such as `mxm`.  It's jarring to be able to view a nice repr of an expression that's clearly invalid, since it seems to imply everything is okay when it obviously isn't.

I don't (yet) want to check whether op (and accum) are valid based on the relevant domains, because this isn't nearly as obvious (and, who knows, maybe some implementations will define special coercion rules).  I don't think we should check index values either (too slow).
