### ISSUE TITLE
grblas.semiring.any_div.binaryop raises error

### ISSUE THREAD

**Issue by jim22k** [metagraph-dev/grblas#77]
`grblas.binary.div` is replaced with `cdiv` and `truediv` and `floordiv` to better match Python's implementation of division.

This change was never applied to the pre-compiled versions of semirings using `div`. Whether or not this same hack should be applied is debatable, but it additionally breaks `grblas.semiring.any_div.binaryop` because it tries to look up `grblas.binary.div` which does not exist.

**Comment by eriknw** [comment]
Good catch!

I'm in favor of `any_cdiv`, `any_floordiv`, and `any_truediv` while removing `any_div`.
